Validate versions in the release preparation (#82)

diff --git a/.github/workflows/create_release_pr.yml b/.github/workflows/create_release_pr.yml
--- a/.github/workflows/create_release_pr.yml
+++ b/.github/workflows/create_release_pr.yml
@@ -40,14 +40,14 @@ jobs:
       - name: Check versions
         run: |
           echo "Checking release version..."
-          if echo ${{ github.event.inputs.release_version }} | grep '^[0-9]+\.[0-9]+\.[0-9]+\(-\(alpha\|beta\|rc[0-9]\+\)\)\?\$' > /dev/null; then
+          if ! [[ "${{ github.event.inputs.release_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc[0-9]+))?$ ]]; then
             echo "Release version is invalid"
             exit 1
           fi
 
           echo "Checking snapshot version..."
-          if echo ${{ github.event.inputs.snapshot_version }} | grep '^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT\$' > /dev/null; then
-            echo "Snapshot version is invalid"
+          if ! [[ "${{ github.event.inputs.snapshot_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]]; then
+            echo "SNAPSHOT version is invalid"
             exit 1
           fi
 
